/* weapons-data.js — Ukrainian war arsenal definitions (extracted from weapons.js) */
const WeaponData = (function() {
  'use strict';
  const WEAPONS = [
    // NEW: Gatling Machine Gun (first available)
    {
      id: 'GATLING', name: 'Gatling Machine Gun', damage: 14,
      fireRate: 0.015, clipSize: 200, maxReserve: 800, reloadTime: 7.0,
      spread: 0.09, auto: true, type: 'GATLING', recoilY: 0.010, recoilX: 0.006,
      barrels: 6, spinUp: 0.3, spinDown: 0.5, description: 'Six rotating barrels, extremely high fire rate.'
    },
    {
      id: 'SHOVEL', name: 'Army Shovel (МПЛ-50)', damage: 35,
      fireRate: 0.25, clipSize: 0, maxReserve: 0, reloadTime: 0,
      spread: 0, auto: true, type: 'MELEE', recoilY: 0, recoilX: 0,
    },
    {
      id: 'MAKAROV', name: 'Makarov PM', damage: 18,
      fireRate: 0.12, clipSize: 8, maxReserve: 48, reloadTime: 1.0,
      spread: 0.02, auto: false, type: 'PISTOL', recoilY: 0.006, recoilX: 0.002,
      quickDraw: true,
    },
    {
      id: 'AK74', name: 'AK-74M', damage: 30,
      fireRate: 0.095, clipSize: 30, maxReserve: 150, reloadTime: 1.8,
      spread: 0.018, auto: true, type: 'ASSAULT', recoilY: 0.013, recoilX: 0.005,
      hasScope: true,
    },
    {
      id: 'RPK74', name: 'RPK-74', damage: 22,
      fireRate: 0.08, clipSize: 45, maxReserve: 180, reloadTime: 3.5,
      spread: 0.035, auto: true, type: 'LMG', recoilY: 0.020, recoilX: 0.010,
    },
    {
      id: 'SVD', name: 'SVD Dragunov', damage: 115,
      fireRate: 0.85, clipSize: 10, maxReserve: 40, reloadTime: 3.5,
      spread: 0.004, auto: false, type: 'SNIPER', hasScope: true, recoilY: 0.040, recoilX: 0.010,
    },
    {
      id: 'PKM', name: 'PKM', damage: 18,
      fireRate: 0.07, clipSize: 100, maxReserve: 250, reloadTime: 4.5,
      spread: 0.048, auto: true, type: 'HMG', recoilY: 0.025, recoilX: 0.012,
    },
    {
      id: 'NLAW', name: 'NLAW', damage: 500,
      fireRate: 2.0, clipSize: 1, maxReserve: 3, reloadTime: 4.0,
      spread: 0, auto: false, type: 'AT', blastRadius: 4, recoilY: 0.060, recoilX: 0.020,
    },
    {
      id: 'STUGNA', name: 'Stugna-P', damage: 800,
      fireRate: 3.0, clipSize: 1, maxReserve: 2, reloadTime: 5.0,
      spread: 0, auto: false, type: 'ATGM', hasScope: true, homing: true, blastRadius: 5, recoilY: 0.050, recoilX: 0.015,
    },
    {
      id: 'M4A1', name: 'M4A1', damage: 30,
      fireRate: 0.09, clipSize: 30, maxReserve: 120, reloadTime: 2.0,
      spread: 0.018, auto: true, type: 'NATO', recoilY: 0.013, recoilX: 0.005,
      hasScope: true,
    },
    {
      id: 'JAVELIN', name: 'FGM-148 Javelin', damage: 1200,
      fireRate: 4.0, clipSize: 1, maxReserve: 2, reloadTime: 6.0,
      spread: 0, auto: false, type: 'AT_HEAVY', hasScope: true, homing: true, blastRadius: 6, recoilY: 0.060, recoilX: 0.020,
    },
    {
      id: 'RPG7', name: 'RPG-7', damage: 350,
      fireRate: 2.5, clipSize: 1, maxReserve: 4, reloadTime: 3.5,
      spread: 0.01, auto: false, type: 'AT_LIGHT', blastRadius: 3.5, recoilY: 0.055, recoilX: 0.018,
    },
    {
      id: 'IGLA', name: 'Igla MANPADS', damage: 600,
      fireRate: 3.5, clipSize: 1, maxReserve: 2, reloadTime: 5.0,
      spread: 0, auto: false, type: 'AA', hasScope: true, homing: true, blastRadius: 4, recoilY: 0.050, recoilX: 0.015,
    },
    {
      id: 'GP25', name: 'GP-25 Grenade Launcher', damage: 150,
      fireRate: 1.5, clipSize: 1, maxReserve: 8, reloadTime: 2.5,
      spread: 0.015, auto: false, type: 'GRENADE', blastRadius: 3, recoilY: 0.035, recoilX: 0.012,
    },
    {
      id: 'SCARH', name: 'FN SCAR-H', damage: 35,
      fireRate: 0.085, clipSize: 20, maxReserve: 100, reloadTime: 2.3,
      spread: 0.016, auto: true, type: 'NATO_HEAVY', recoilY: 0.018, recoilX: 0.007,
      hasScope: true,
    },
    {
      id: 'DSHK', name: 'DShK', damage: 45,
      fireRate: 0.10, clipSize: 50, maxReserve: 150, reloadTime: 5.0,
      spread: 0.05, auto: true, type: 'HMG_HEAVY', recoilY: 0.028, recoilX: 0.014,
    },
    {
      id: 'MOLOTOV', name: 'Molotov Cocktail', damage: 80,
      fireRate: 1.0, clipSize: 1, maxReserve: 5, reloadTime: 0.5,
      spread: 0.02, auto: false, type: 'INCENDIARY', blastRadius: 3, recoilY: 0.010, recoilX: 0.005,
    },
    // ── 7 new weapons ──────────────────────────────────────
    {
      id: 'MG3', name: 'MG3 Machine Gun', damage: 24,
      fireRate: 0.065, clipSize: 120, maxReserve: 360, reloadTime: 5.5,
      spread: 0.055, auto: true, type: 'MACHINEGUN', recoilY: 0.022, recoilX: 0.011,
      hasScope: true,
    },
    {
      id: 'MP5', name: 'MP5 SMG', damage: 18,
      fireRate: 0.06, clipSize: 30, maxReserve: 150, reloadTime: 2.0,
      spread: 0.04, auto: true, type: 'SMG', recoilY: 0.010, recoilX: 0.005,
    },
    {
      id: 'BARRETTM82', name: 'Barrett M82', damage: 250,
      fireRate: 1.5, clipSize: 10, maxReserve: 30, reloadTime: 4.0,
      spread: 0.002, auto: false, type: 'AMR', hasScope: true, recoilY: 0.045, recoilX: 0.012,
    },
    {
      id: 'MINIGUN', name: 'M134 Minigun', damage: 12,
      fireRate: 0.02, clipSize: 500, maxReserve: 1000, reloadTime: 8.0,
      spread: 0.08, auto: true, type: 'MINIGUN', recoilY: 0.012, recoilX: 0.008,
    },
    {
      id: 'CROSSBOW', name: 'Tactical Crossbow', damage: 130,
      fireRate: 1.2, clipSize: 1, maxReserve: 15, reloadTime: 1.8,
      spread: 0.006, auto: false, type: 'SILENT', recoilY: 0, recoilX: 0,
    },
    {
      id: 'FLAMETHROWER', name: 'RPO-A Shmel', damage: 200,
      fireRate: 2.0, clipSize: 1, maxReserve: 3, reloadTime: 3.5,
      spread: 0.03, auto: false, type: 'THERMOBARIC', blastRadius: 5, recoilY: 0.060, recoilX: 0.020,
    },
    {
      id: 'DOUBLEBARREL', name: 'IZH-43 Shotgun', damage: 120,
      fireRate: 0.3, clipSize: 2, maxReserve: 24, reloadTime: 2.0,
      spread: 0.12, auto: false, type: 'SHOTGUN', recoilY: 0.035, recoilX: 0.015,
    },
    // ── 3 new special weapons ──────────────────────────────
    {
      id: 'CLAYMORE', name: 'M18 Claymore Mine', damage: 300,
      fireRate: 1.5, clipSize: 1, maxReserve: 3, reloadTime: 2.0,
      spread: 0, auto: false, type: 'MINE', blastRadius: 5, recoilY: 0, recoilX: 0,
    },
    {
      id: 'SMOKE', name: 'Smoke Grenade', damage: 0,
      fireRate: 1.0, clipSize: 1, maxReserve: 4, reloadTime: 1.5,
      spread: 0.02, auto: false, type: 'SMOKE', blastRadius: 6, recoilY: 0.005, recoilX: 0.002,
    },
    {
      id: 'FLASHBANG', name: 'M84 Flashbang', damage: 5,
      fireRate: 1.2, clipSize: 1, maxReserve: 3, reloadTime: 1.5,
      spread: 0.02, auto: false, type: 'FLASHBANG', blastRadius: 8, recoilY: 0.005, recoilX: 0.002,
    },
    // ── 10 new weapons (B16) ──────────────────────────────
    {
      id: 'AK12', name: 'AK-12', damage: 32,
      fireRate: 0.085, clipSize: 30, maxReserve: 150, reloadTime: 2.1,
      spread: 0.018, auto: true, type: 'ASSAULT', recoilY: 0.014, recoilX: 0.005,
    },
    {
      id: 'P90', name: 'FN P90', damage: 20,
      fireRate: 0.055, clipSize: 50, maxReserve: 200, reloadTime: 2.3,
      spread: 0.032, auto: true, type: 'SMG', recoilY: 0.009, recoilX: 0.004,
    },
    {
      id: 'AT4', name: 'AT4 Launcher', damage: 450,
      fireRate: 2.5, clipSize: 1, maxReserve: 3, reloadTime: 4.5,
      spread: 0.005, auto: false, type: 'AT_LIGHT', blastRadius: 4, recoilY: 0.055, recoilX: 0.018,
    },
    {
      id: 'GLOCK', name: 'Glock 17', damage: 17,
      fireRate: 0.10, clipSize: 17, maxReserve: 68, reloadTime: 1.3,
      spread: 0.025, auto: false, type: 'PISTOL', recoilY: 0.007, recoilX: 0.003,
    },
    {
      id: 'KS23', name: 'KS-23 Shotgun', damage: 180,
      fireRate: 0.8, clipSize: 3, maxReserve: 15, reloadTime: 3.0,
      spread: 0.10, auto: false, type: 'SHOTGUN', recoilY: 0.040, recoilX: 0.018,
    },
    {
      id: 'AGS17', name: 'AGS-17 Grenade MG', damage: 80,
      fireRate: 0.35, clipSize: 6, maxReserve: 30, reloadTime: 4.0,
      spread: 0.04, auto: false, type: 'GRENADE', blastRadius: 3.5, recoilY: 0.030, recoilX: 0.015,
    },
    {
      id: 'VSS', name: 'VSS Vintorez', damage: 42,
      fireRate: 0.12, clipSize: 20, maxReserve: 80, reloadTime: 2.5,
      spread: 0.010, auto: true, type: 'SILENT', hasScope: true, recoilY: 0.012, recoilX: 0.005,
    },
    {
      id: 'STINGER', name: 'FIM-92 Stinger', damage: 700,
      fireRate: 3.5, clipSize: 1, maxReserve: 2, reloadTime: 5.5,
      spread: 0, auto: false, type: 'AA', hasScope: true, homing: true, blastRadius: 5, recoilY: 0.050, recoilX: 0.015,
    },
    {
      id: 'THROWKNIFE', name: 'Throwing Knife', damage: 90,
      fireRate: 0.5, clipSize: 1, maxReserve: 8, reloadTime: 0.3,
      spread: 0.008, auto: false, type: 'SILENT', recoilY: 0, recoilX: 0,
    },
    {
      id: 'C4', name: 'C4 Explosive', damage: 500,
      fireRate: 1.5, clipSize: 1, maxReserve: 3, reloadTime: 2.0,
      spread: 0, auto: false, type: 'EXPLOSIVE', blastRadius: 7, recoilY: 0, recoilX: 0,
    },
    {
      id: 'DRONEJAMMER', name: 'Drone Jammer Rifle', damage: 8,
      fireRate: 0.14, clipSize: 30, maxReserve: 120, reloadTime: 2.2,
      spread: 0.025, auto: true, type: 'JAMMER', recoilY: 0.005, recoilX: 0.002,
      description: 'EMP pulse rifle. Disables enemy drones and damages electronics in a forward cone.',
    },
    {
      id: 'AXE', name: 'Combat Axe', damage: 75,
      fireRate: 0.45, clipSize: 0, maxReserve: 0, reloadTime: 0,
      spread: 0, auto: false, type: 'MELEE', recoilY: 0, recoilX: 0,
      description: 'Heavy chopping axe. Brutal close-quarters melee with high single-hit damage.',
    },
    // ── 5 Ukraine-war iconic weapons ──────────────────────────
    {
      id: 'AKS74U', name: 'AKS-74U (Krinkov)', damage: 24,
      fireRate: 0.072, clipSize: 30, maxReserve: 150, reloadTime: 1.9,
      spread: 0.030, auto: true, type: 'ASSAULT', recoilY: 0.016, recoilX: 0.007,
      description: 'Compact AK carbine. Used by both sides — ubiquitous in trench warfare.',
    },
    {
      id: 'M72LAW', name: 'M72 LAW', damage: 420,
      fireRate: 2.2, clipSize: 1, maxReserve: 3, reloadTime: 3.8,
      spread: 0.006, auto: false, type: 'AT_LIGHT', blastRadius: 3.8, recoilY: 0.058, recoilX: 0.020,
      description: 'Lightweight disposable AT rocket from the US/NATO. One-shot, then drop it.',
    },
    {
      id: 'PANZERFAUST3', name: 'Panzerfaust 3', damage: 650,
      fireRate: 2.8, clipSize: 1, maxReserve: 2, reloadTime: 4.2,
      spread: 0.004, auto: false, type: 'AT', blastRadius: 4.5, recoilY: 0.060, recoilX: 0.022,
      description: 'German AT rocket donated to Ukraine. Tandem-charge warhead defeats ERA.',
    },
    {
      id: 'NSVHMG', name: 'NSV/Utyes 12.7mm', damage: 55,
      fireRate: 0.13, clipSize: 50, maxReserve: 150, reloadTime: 5.5,
      spread: 0.040, auto: true, type: 'HMG_HEAVY', recoilY: 0.032, recoilX: 0.016,
      description: 'Soviet 12.7mm HMG used extensively by Russian forces. Heavier than DShK, more stable.',
    },
    {
      id: 'FORT500', name: 'Fort-500 (Ukrainian)', damage: 160,
      fireRate: 0.70, clipSize: 5, maxReserve: 20, reloadTime: 2.8,
      spread: 0.09, auto: false, type: 'SHOTGUN', recoilY: 0.038, recoilX: 0.016,
      description: 'Ukrainian-made pump-action shotgun. Domestic production — armed the Territorial Defense.',
    },
    // ── 3 additional Ukraine-conflict weapons ─────────────────
    {
      id: 'MALYUK', name: 'Malyuk (Vulcan) Bullpup', damage: 28,
      fireRate: 0.075, clipSize: 30, maxReserve: 180, reloadTime: 2.0,
      spread: 0.026, auto: true, type: 'ASSAULT', recoilY: 0.014, recoilX: 0.006,
      description: 'Ukrainian-designed bullpup assault rifle. Compact, ergonomic, domestically produced for the UAF.',
    },
    {
      id: 'CARLGUSTAF', name: 'Carl Gustaf M3 (MAAWS)', damage: 750,
      fireRate: 3.2, clipSize: 1, maxReserve: 4, reloadTime: 4.5,
      spread: 0.005, auto: false, type: 'AT', blastRadius: 4.8, recoilY: 0.062, recoilX: 0.024,
      description: '84mm recoilless rifle supplied by US, Sweden, and others. Versatile platform for armor, bunkers, and area denial.',
    },
    {
      id: 'M240B', name: 'M240B GPMG (7.62mm)', damage: 32,
      fireRate: 0.095, clipSize: 100, maxReserve: 400, reloadTime: 4.2,
      spread: 0.032, auto: true, type: 'LMG', recoilY: 0.018, recoilX: 0.010,
      description: 'NATO 7.62mm belt-fed machine gun. Supplied to Ukraine. Reliable sustained-fire platform.',
    },
    {
      id: 'PKPECHENEG', name: 'PKP Pecheneg (7.62mm MG)', damage: 34,
      fireRate: 0.085, clipSize: 100, maxReserve: 400, reloadTime: 5.0,
      spread: 0.028, auto: true, type: 'LMG', recoilY: 0.016, recoilX: 0.008,
      description: 'Improved Russian PKM variant with fixed heavy barrel and integral bipod. Used extensively by Russian forces in Ukraine.',
    },
    {
      id: 'SPG9', name: 'SPG-9 Kopye (73mm)', damage: 550,
      fireRate: 5.0, clipSize: 1, maxReserve: 5, reloadTime: 5.5,
      spread: 0.006, auto: false, type: 'AT', blastRadius: 4.2, recoilY: 0.055, recoilX: 0.020,
      description: 'Soviet 73mm recoilless rifle. Tripod-mounted or vehicle-mounted. Widely used by both Ukrainian and Russian forces for AT and bunker-busting.',
    },
    {
      id: 'HK416', name: 'HK416 A5', damage: 31,
      fireRate: 0.080, clipSize: 30, maxReserve: 150, reloadTime: 2.4,
      spread: 0.020, auto: true, type: 'ASSAULT', recoilY: 0.013, recoilX: 0.005,
      description: 'German assault rifle supplied to Ukraine via Germany and other NATO partners. Piston-driven, highly reliable in harsh conditions.',
    },
    {
      id: 'RGD5', name: 'RGD-5 Frag Grenade', damage: 180,
      fireRate: 1.2, clipSize: 4, maxReserve: 12, reloadTime: 1.0,
      spread: 0.0, auto: false, type: 'GRENADE', recoilY: 0.0, recoilX: 0.0,
      description: 'Soviet fragmentation grenade. Standard issue across former Soviet armies. Effective blast radius ~15m. Both sides use these extensively.',
    },
    {
      id: 'SPIKE_LR', name: 'Spike LR ATGM', damage: 1100,
      fireRate: 3.0, clipSize: 1, maxReserve: 4, reloadTime: 4.5,
      spread: 0.0, auto: false, type: 'ATGM', recoilY: 0.02, recoilX: 0.0,
      description: 'Israeli fire-and-forget anti-tank guided missile. Used extensively by Ukraine. Lock-on top-attack mode defeats ERA. Range 200-4000m.',
    },
    {
      id: 'MILAN', name: 'MILAN ATGM', damage: 850,
      fireRate: 4.0, clipSize: 1, maxReserve: 3, reloadTime: 5.0,
      spread: 0.0, auto: false, type: 'ATGM', recoilY: 0.015, recoilX: 0.0,
      description: 'Franco-German wire-guided anti-tank missile. Germany, France and Belgium supplied hundreds to Ukraine. Tandem warhead, SACLOS guidance.',
    },
    {
      id: 'MP7', name: 'HK MP7A2', damage: 20,
      fireRate: 0.055, clipSize: 40, maxReserve: 160, reloadTime: 2.1,
      spread: 0.018, auto: true, type: 'SMG', recoilY: 0.009, recoilX: 0.004,
      description: 'German compact PDW using 4.6×30mm armour-piercing rounds. Supplied by Germany. Compact enough for vehicle crews and special forces.',
    },
    {
      id: 'KORD', name: 'Kord 12.7mm HMG', damage: 65,
      fireRate: 0.105, clipSize: 50, maxReserve: 200, reloadTime: 4.0,
      spread: 0.030, auto: true, type: 'HMG', recoilY: 0.04, recoilX: 0.012,
      description: 'Russian 12.7×108mm heavy machine gun. Successor to NSV/Utyes. Used on BTR-82A, T-80, T-90 vehicles. Effective against infantry and light armour to 2000m.',
    },
    {
      id: 'BROWNING_M2', name: 'M2HB Browning .50cal', damage: 60,
      fireRate: 0.115, clipSize: 50, maxReserve: 200, reloadTime: 4.2,
      spread: 0.028, auto: true, type: 'HMG', recoilY: 0.042, recoilX: 0.014,
      description: 'American .50-caliber heavy machine gun. Iconic NATO HMG mounted on HMMWVs, M113s and M2A2 Bradleys supplied to Ukraine. "Ma Deuce" — in service since 1933.',
    },
    {
      id: 'ZU_23_2', name: 'ZU-23-2 (23mm AA Autocannon)', damage: 85,
      fireRate: 0.075, clipSize: 50, maxReserve: 200, reloadTime: 5.0,
      spread: 0.022, auto: true, type: 'HMG', recoilY: 0.055, recoilX: 0.018,
      description: 'Soviet twin 23×152mm autocannon. Both sides improvised this AA gun on trucks as a ground assault weapon. Devastating against infantry, light vehicles and drones.',
    },
    {
      id: 'FPV_DRONE', name: 'FPV Kamikaze Drone', damage: 400,
      fireRate: 8.0, clipSize: 1, maxReserve: 3, reloadTime: 6.5,
      spread: 0, auto: false, type: 'AT_LIGHT', recoilY: 0.015, recoilX: 0.004,
      blastRadius: 5, homing: false,
      description: 'First-person-view quadcopter with RKG-3 grenade or PG-7 warhead. Most prolific weapon in 2024-2025 Ukraine war. Guided by FPV goggles to target.',
    },
    {
      id: 'KORNET', name: '9M133 Kornet ATGM', damage: 1050,
      fireRate: 4.5, clipSize: 1, maxReserve: 3, reloadTime: 5.8,
      spread: 0, auto: false, type: 'ATGM', recoilY: 0.060, recoilX: 0.018,
      blastRadius: 7, homing: true, hasScope: true,
      description: 'Russian laser-guided ATGM. Dual tandem warhead defeats ERA-equipped T-80/T-90. Used by Russian forces to destroy Ukrainian armour; some captured units used by Ukraine.',
    },
    {
      id: 'RPG26', name: 'RPG-26 Aglen (disposable)', damage: 390,
      fireRate: 3.2, clipSize: 1, maxReserve: 2, reloadTime: 3.8,
      spread: 0.012, auto: false, type: 'AT_LIGHT', recoilY: 0.070, recoilX: 0.022,
      blastRadius: 3.5,
      description: 'Single-shot disposable 72.5mm rocket launcher. Used by both sides throughout the war. Lighter and simpler than RPG-7 — fire and discard the tube.',
    },
    {
      id: 'HIMARS', name: 'M142 HIMARS (GMLRS Strike)', damage: 3000,
      fireRate: 12.0, clipSize: 1, maxReserve: 1, reloadTime: 14.0,
      spread: 0, auto: false, type: 'AT_HEAVY', recoilY: 0.010, recoilX: 0.003,
      blastRadius: 25, homing: true,
      description: 'US M142 High Mobility Artillery Rocket System. GMLRS precision rocket to 84km. Decisive NATO weapon destroying Russian depots and supply lines across Ukraine.',
    },
    {
      id: 'F1_GRENADE', name: 'F-1 "Limonka" Grenade', damage: 220,
      fireRate: 1.8, clipSize: 3, maxReserve: 9, reloadTime: 1.5,
      spread: 0, auto: false, type: 'GRENADE', recoilY: 0.010, recoilX: 0.003,
      blastRadius: 6,
      description: 'Soviet F-1 fragmentation grenade ("Limonka" = little lemon). Heavier frag pattern than RGD-5 — lethal radius ~5m. Both sides stockpile thousands.',
    },
    {
      id: 'MAXIM1910', name: 'Maxim M1910 (7.62mm)', damage: 28,
      fireRate: 0.10, clipSize: 250, maxReserve: 500, reloadTime: 7.0,
      spread: 0.025, auto: true, type: 'LMG', recoilY: 0.025, recoilX: 0.008,
      description: 'WW1-era water-cooled machine gun still seen in Ukraine. Belt-fed, tripod-mounted. Filmed in combat in 2022-2024. Soviet/Russian mil doctrine: "never throw anything away."',
    },
    {
      id: 'BM21_GRAD', name: 'BM-21 Grad MLRS (Call Fire)', damage: 2800,
      fireRate: 14.0, clipSize: 1, maxReserve: 1, reloadTime: 16.0,
      spread: 0.02, auto: false, type: 'AT_HEAVY', recoilY: 0.008, recoilX: 0.002,
      blastRadius: 28, homing: false,
      description: 'Soviet BM-21 Grad 40-round 122mm MLRS. Russia\'s most used artillery system in Ukraine — responsible for the majority of casualties. Wide-area saturation fire.',
    },
    {
      id: 'TAVOR_X95', name: 'IWI Tavor X95 (5.56mm)', damage: 29,
      fireRate: 0.085, clipSize: 30, maxReserve: 120, reloadTime: 2.2,
      spread: 0.018, auto: true, type: 'RIFLE', recoilY: 0.022, recoilX: 0.008,
      description: 'Israeli bullpup assault rifle. Supplied to Ukrainian units through various channels. Compact (590mm overall), very reliable in urban environments.',
    },
    {
      id: 'TOW_BGM71', name: 'BGM-71 TOW ATGM', damage: 950,
      fireRate: 5.5, clipSize: 1, maxReserve: 3, reloadTime: 7.0,
      spread: 0, auto: false, type: 'ATGM', recoilY: 0.045, recoilX: 0.012,
      blastRadius: 6, homing: true, hasScope: true,
      description: 'US Tube-launched Optically tracked Wire-guided ATGM. Thousands supplied to Ukraine. BGM-71F warhead penetrates 900mm RHA. Range 3750m, in service since 1970.',
    },
    {
      id: 'RPG29', name: 'RPG-29 Vampir (tandem)', damage: 680,
      fireRate: 4.0, clipSize: 1, maxReserve: 2, reloadTime: 5.0,
      spread: 0.008, auto: false, type: 'AT_LIGHT', recoilY: 0.075, recoilX: 0.024,
      blastRadius: 5,
      description: 'Russian RPG-29 Vampir. 105mm tandem HEAT warhead defeats ERA-equipped tanks. Two-piece tube design. Used by Russian forces and Syrian Army; some captured by Ukraine.',
    },
    {
      id: 'STARSTREAK', name: 'Starstreak HVM (UK)', damage: 750,
      fireRate: 4.2, clipSize: 1, maxReserve: 3, reloadTime: 5.5,
      spread: 0, auto: false, type: 'AA', recoilY: 0.040, recoilX: 0.012,
      blastRadius: 4, homing: true, hasScope: true,
      description: 'UK Thales Starstreak high-velocity missile. Fires 3 laser-guided tungsten darts at Mach 3.5. Supplied to Ukraine for drone/helicopter defense in 2022.',
    },
    {
      id: 'AKM', name: 'AKM/AK-47 (7.62×39mm)', damage: 32,
      fireRate: 0.095, clipSize: 30, maxReserve: 120, reloadTime: 2.3,
      spread: 0.022, auto: true, type: 'RIFLE', recoilY: 0.030, recoilX: 0.012,
      description: 'AKM — the mass-produced AK-47 variant. 7.62×39mm round. What most Russian conscripts and older units carry. Captured examples are primary loot on the Kyiv front.',
    },
    {
      id: 'AN94', name: 'AN-94 Abakan (5.45mm)', damage: 33,
      fireRate: 0.080, clipSize: 30, maxReserve: 120, reloadTime: 2.4,
      spread: 0.015, auto: true, type: 'RIFLE', recoilY: 0.018, recoilX: 0.006,
      description: 'Russian AN-94 Abakan. 2-round hyperburst at 1800rpm before cycling. Used by Russian Spetsnaz and elite units in Ukraine. Unusual pulley-delay mechanism.',
    },
    {
      id: 'M67_GRENADE', name: 'M67 Frag Grenade (NATO)', damage: 210,
      fireRate: 1.8, clipSize: 3, maxReserve: 9, reloadTime: 1.5,
      spread: 0, auto: false, type: 'GRENADE', recoilY: 0.010, recoilX: 0.003,
      blastRadius: 6,
      description: 'US M67 spherical fragmentation grenade. NATO standard issue. Over a million delivered to Ukraine. Lethal radius ~5m, casualty radius ~15m.',
    },
    {
      id: 'SWITCHBLADE300', name: 'Switchblade 300 (loitering)', damage: 320,
      fireRate: 10.0, clipSize: 1, maxReserve: 2, reloadTime: 8.0,
      spread: 0, auto: false, type: 'AT_LIGHT', recoilY: 0.008, recoilX: 0.002,
      blastRadius: 4, homing: true,
      description: 'AeroVironment Switchblade 300. US "kamikaze" loitering munition. Tube-launched, electrically propelled, anti-personnel warhead. Over 700 sent to Ukraine.',
    },
    {
      id: 'SAIGA12', name: 'Saiga-12 Combat Shotgun', damage: 130,
      fireRate: 0.42, clipSize: 10, maxReserve: 40, reloadTime: 2.8,
      spread: 0.080, auto: false, type: 'SHOTGUN', recoilY: 0.055, recoilX: 0.018,
      description: 'Russian Saiga-12 semi-automatic shotgun based on AK action. 12-gauge, box magazine. Used by both sides as an improvised close-quarters weapon and for drone interdiction.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'RPG18', name: 'RPG-18 Mukha (64mm disposable)', damage: 340,
      fireRate: 3.0, clipSize: 1, maxReserve: 2, reloadTime: 3.5,
      spread: 0.015, auto: false, type: 'AT_LIGHT', recoilY: 0.072, recoilX: 0.024,
      blastRadius: 3.0,
      description: 'Soviet 64mm single-shot disposable AT rocket. Both sides carry these in their webbing. Light, simple, plentiful — the default close-range AT option for Russian conscripts and Ukrainian TDF alike.',
    },
    {
      id: 'PODNOS82', name: '2B14 Podnos 82mm Mortar', damage: 850,
      fireRate: 5.5, clipSize: 1, maxReserve: 8, reloadTime: 4.0,
      spread: 0.055, auto: false, type: 'EXPLOSIVE', recoilY: 0.006, recoilX: 0.002,
      blastRadius: 9,
      description: '82mm infantry mortar. The most common single artillery piece in the Ukraine trench war — both sides fire thousands of rounds daily. Drop-in-tube operation, 3km max range, 4 rounds/min.',
    },
    {
      id: 'OTS14', name: 'OTs-14 Groza (Spetsnaz bullpup)', damage: 26,
      fireRate: 0.068, clipSize: 30, maxReserve: 120, reloadTime: 2.2,
      spread: 0.020, auto: true, type: 'ASSAULT', recoilY: 0.012, recoilX: 0.005,
      description: 'Russian OTs-14 Groza bullpup. 9×39mm subsonic with integral suppressor and GP-25 underbarrel grenade launcher. Used by FSB and Spetsnaz in Ukraine. Nearly inaudible at distance.',
    },
    {
      id: 'PP19', name: 'PP-19 Bizon (64-round helical)', damage: 16,
      fireRate: 0.058, clipSize: 64, maxReserve: 192, reloadTime: 3.2,
      spread: 0.025, auto: true, type: 'SMG', recoilY: 0.008, recoilX: 0.003,
      description: 'Russian PP-19 Bizon. 9mm with distinctive 64-round helical (screw) magazine under the barrel. Used by Russian MVD, OMON and vehicle crews in Ukraine. Excellent CQB capacity.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'FAB500', name: 'FAB-500 Glide Bomb (UMPK kit)', damage: 5000,
      fireRate: 20.0, clipSize: 1, maxReserve: 1, reloadTime: 22.0,
      spread: 0.010, auto: false, type: 'EXPLOSIVE', recoilY: 0.003, recoilX: 0.001,
      blastRadius: 18, homing: false,
      description: 'Russian 500kg gravity bomb with UMPK glide-navigation kit. Released from Su-34/35 at 80km stand-off. Impossible to intercept with Ukrainian SAMs. Demolished Avdiivka, Bakhmut, Kherson. One bomb levels an apartment block.',
    },
    {
      id: 'M777', name: 'M777 155mm Howitzer (Call Fire)', damage: 1400,
      fireRate: 11.0, clipSize: 1, maxReserve: 3, reloadTime: 13.0,
      spread: 0.018, auto: false, type: 'AT_HEAVY', recoilY: 0.006, recoilX: 0.002,
      blastRadius: 12, homing: false,
      description: 'US M777A2 155mm ultra-light towed howitzer. 120+ supplied to Ukraine. Fires Excalibur GPS-guided rounds to 40km. NATO standard 155mm — the backbone of Ukrainian counteroffensive firepower since 2022.',
    },
    {
      id: 'STRELA2', name: 'Strela-2M (SA-7 MANPADS)', damage: 420,
      fireRate: 4.8, clipSize: 1, maxReserve: 2, reloadTime: 5.0,
      spread: 0, auto: false, type: 'AA', recoilY: 0.038, recoilX: 0.010,
      blastRadius: 3.5, homing: true,
      description: 'Soviet 1st-generation shoulder-launched MANPADS. Older than Igla/Stinger but vastly more numerous — both sides draw from Soviet-era depots. Infrared heat-seeking. Effective against helicopters and low-altitude aircraft.',
    },
    {
      id: 'DROPDRONE', name: 'Commercial Drop Drone (VOG-25)', damage: 180,
      fireRate: 6.0, clipSize: 2, maxReserve: 6, reloadTime: 4.5,
      spread: 0.04, auto: false, type: 'EXPLOSIVE', recoilY: 0.003, recoilX: 0.001,
      blastRadius: 4, homing: false,
      description: 'DJI Mavic-3 commercial drone carrying a VOG-25 grenade in a 3D-printed clamp. Ukrainian innovation now responsible for more trench casualties than artillery in some sectors. Cheap, available, and terrifying.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'BAYRAKTAR', name: 'Bayraktar TB2 (Strike Drone)', damage: 1800,
      fireRate: 14.0, clipSize: 1, maxReserve: 2, reloadTime: 16.0,
      spread: 0, auto: false, type: 'AT_HEAVY', recoilY: 0.004, recoilX: 0.001,
      blastRadius: 10, homing: true,
      description: 'Turkish Bayraktar TB2 UCAV. Ukraine had 35 by Feb 2022. Armed with MAM-L smart munition. Dominated the 2022 Kyiv defense — viral footage worldwide. Now countered by Russian EW but still operational in modified roles.',
    },
    {
      id: 'TOS1A', name: 'TOS-1A Buratino (Thermobaric MLRS)', damage: 2500,
      fireRate: 16.0, clipSize: 1, maxReserve: 1, reloadTime: 18.0,
      spread: 0.008, auto: false, type: 'THERMOBARIC', recoilY: 0.005, recoilX: 0.002,
      blastRadius: 16, homing: false,
      description: 'Russian TOS-1A Solntsepyok. 220mm thermobaric MLRS on T-72 chassis. 24-round ripple creates 40,000m² fireball. Ukraine captured several in 2022. The most horrific area-denial weapon in the war.',
    },
    {
      id: 'DP27', name: 'DP-27/28 "Degtyarev" LMG', damage: 26,
      fireRate: 0.095, clipSize: 47, maxReserve: 141, reloadTime: 4.0,
      spread: 0.038, auto: true, type: 'LMG', recoilY: 0.022, recoilX: 0.010,
      description: 'Soviet WW2-era DP-27 light machine gun. Still filmed in Ukraine trenches 2022-2025 — both sides dip into old reserve stocks. 47-round pan magazine sits on top. Nicknamed "gramophone" or "record player."',
    },
    {
      id: 'SV98', name: 'SV-98 Precision Sniper Rifle', damage: 185,
      fireRate: 1.5, clipSize: 10, maxReserve: 30, reloadTime: 4.5,
      spread: 0.002, auto: false, type: 'SNIPER', hasScope: true, recoilY: 0.045, recoilX: 0.012,
      description: 'Russian SV-98 bolt-action 7.62×54mmR. Used by Russian snipers for methodical counter-sniper work in static trench lines. More accurate than SVD but slower. Deployed from dedicated hides at 800-1000m.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'LANCET3', name: 'Lancet-3 (Zala loitering munition)', damage: 520,
      fireRate: 9.0, clipSize: 1, maxReserve: 2, reloadTime: 7.0,
      spread: 0, auto: false, type: 'AT_LIGHT', recoilY: 0.004, recoilX: 0.001,
      blastRadius: 5, homing: true,
      description: 'Russian Zala Lancet-3 loitering munition. Distinctive X-wing design at nose and tail. 3kg warhead with fragmentation/shaped-charge option. Camera-guided via operator. Responsible for destroying hundreds of Ukrainian howitzers, tanks, and radar systems 2023-2025.',
    },
    {
      id: 'STORMSHADOW', name: 'Storm Shadow/SCALP-EG Cruise Missile', damage: 6000,
      fireRate: 20.0, clipSize: 1, maxReserve: 1, reloadTime: 22.0,
      spread: 0, auto: false, type: 'AT_HEAVY', recoilY: 0.002, recoilX: 0.001,
      blastRadius: 18, homing: true,
      description: 'UK/French Matra Storm Shadow / SCALP-EG standoff cruise missile. 450kg BROACH warhead penetrates hardened bunkers. Range >250km. Air-launched from Su-24M. UK delivery 2023 transformed Ukrainian deep-strike capability — hit Kerch Bridge, Crimea HQs, Sevastopol fleet.',
    },
    {
      id: 'ASVAL', name: 'AS Val (9×39mm suppressed)', damage: 42,
      fireRate: 0.080, clipSize: 20, maxReserve: 80, reloadTime: 2.5,
      spread: 0.014, auto: true, type: 'RIFLE', recoilY: 0.016, recoilX: 0.006,
      description: 'Russian AS Val assault rifle with integral suppressor. Fires subsonic 9×39mm SP-5/SP-6 armour-piercing rounds. Issued to GRU Spetsnaz and elite Rosgvardia. Integral suppressor is non-removable. Used by Russian special forces in Kyiv suburb raids February-March 2022.',
    },
    {
      id: 'OSV96', name: 'OSV-96 12.7mm Anti-Material', damage: 240,
      fireRate: 2.0, clipSize: 5, maxReserve: 20, reloadTime: 5.0,
      spread: 0.003, auto: false, type: 'SNIPER', hasScope: true, recoilY: 0.055, recoilX: 0.016,
      description: 'Russian OSV-96 12.7×108mm anti-material rifle. Folding stock for vehicle transport. Used to defeat light armour, crew-served weapons, and enemy snipers at 1500m+. Both sides deploy heavy anti-material rifles to neutralise each other\'s entrenched positions.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'NEPTUNE', name: 'Neptune R-360 Anti-Ship Missile', damage: 8000,
      fireRate: 20.0, clipSize: 1, maxReserve: 1, reloadTime: 25.0,
      spread: 0, auto: false, type: 'AT_HEAVY', recoilY: 0.003, recoilX: 0.001,
      blastRadius: 22, homing: true,
      description: 'Ukrainian R-360 Neptune subsonic cruise missile. Two Neptune missiles sank the Russian cruiser Moskva on 13 April 2022 — the largest warship sunk in combat since the Falklands. Sea-skimming at 10m altitude, 280km range. Coastal defense system converted to land strike.',
    },
    {
      id: 'METIS_M1', name: 'Metis-M1 (9M131) ATGM', damage: 620,
      fireRate: 5.5, clipSize: 1, maxReserve: 4, reloadTime: 6.0,
      spread: 0, auto: false, type: 'ATGM', recoilY: 0.040, recoilX: 0.010,
      blastRadius: 5, homing: true, hasScope: true,
      description: 'Russian 9M131 Metis-M1 ATGM. Successor to 9M115 Metis. Tandem warhead on tripod-mounted launcher. Portable two-man system. Used extensively by Russian motorised rifle companies in Ukraine for direct AT fire. Wire-guided with 1.5km range.',
    },
    {
      id: 'M249SAW', name: 'M249 SAW (FN Minimi 5.56mm)', damage: 24,
      fireRate: 0.068, clipSize: 200, maxReserve: 600, reloadTime: 5.5,
      spread: 0.032, auto: true, type: 'LMG', recoilY: 0.018, recoilX: 0.008,
      description: 'US M249 Squad Automatic Weapon / FN Minimi. 5.56×45mm belt or STANAG mag. Supplied by US to Ukraine as part of equipment packages. 850rpm cyclic. Standard NATO squad fire support weapon — lighter than PKM but high sustained fire rate.',
    },
    {
      id: 'RPG30', name: 'RPG-30 Kryuk (precursor rocket)', damage: 520,
      fireRate: 3.8, clipSize: 1, maxReserve: 2, reloadTime: 4.5,
      spread: 0.006, auto: false, type: 'AT_LIGHT', recoilY: 0.072, recoilX: 0.022,
      blastRadius: 4.5,
      description: 'Russian RPG-30 "Hook". Unique dual-tube design: fires a small precursor rocket to trigger ERA, then the main 105mm tandem warhead follows. Specifically designed to defeat Kontakt-5 and Trophy active protection systems. Issued to Russian forces in Ukraine.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'SHAHED136', name: 'Shahed-136 / Geranium-2 Drone', damage: 1200,
      fireRate: 12.0, clipSize: 1, maxReserve: 3, reloadTime: 10.0,
      spread: 0, auto: false, type: 'INCENDIARY', recoilY: 0.002, recoilX: 0.001,
      blastRadius: 8, homing: true,
      description: 'Iranian Shahed-136 loitering munition — designated Geranium-2 by Russia. Delta-wing suicide drone used in mass swarm attacks on Ukrainian cities 2022-2025. Visible on radar but cheap enough to overwhelm air defense. Kyiv residents hear the distinctive lawn-mower engine at night.',
    },
    {
      id: 'AGM88HARM', name: 'AGM-88 HARM (Anti-Radiation Missile)', damage: 3500,
      fireRate: 16.0, clipSize: 1, maxReserve: 2, reloadTime: 18.0,
      spread: 0, auto: false, type: 'AT_HEAVY', recoilY: 0.003, recoilX: 0.001,
      blastRadius: 14, homing: true,
      description: 'US AGM-88 High-speed Anti-Radiation Missile. Homes on radar emissions. Ukraine adapted its MiG-29s to fire HARM in 2022, destroying dozens of Russian Buk and S-300 batteries. Range 150km at Mach 2. Pivotal in degrading Russian radar coverage over Ukraine.',
    },
    {
      id: 'RGO78', name: 'RGO-78 Defensive Frag Grenade', damage: 230,
      fireRate: 1.8, clipSize: 3, maxReserve: 9, reloadTime: 1.5,
      spread: 0, auto: false, type: 'GRENADE', recoilY: 0.010, recoilX: 0.003,
      blastRadius: 6,
      description: 'Russian RGO-78 defensive fragmentation grenade. Dual-pattern fragmentation liner — both inner and outer shells fragment, doubling coverage vs RGD-5. Standard issue Russian ground forces. Found in vast quantities at abandoned Russian positions around Kyiv.',
    },
    {
      id: 'GEPARD35', name: 'Gepard Flakpanzer (35mm AA)', damage: 90,
      fireRate: 0.040, clipSize: 340, maxReserve: 680, reloadTime: 8.0,
      spread: 0.018, auto: true, type: 'HMG', recoilY: 0.035, recoilX: 0.014,
      description: 'German Flakpanzer Gepard twin 35mm AA autocannon. Germany supplied 30+ to Ukraine — first time Germany sent heavy weapons. Proved devastating against Shahed drones, helicopters, and low-flying jets. Oerlikon KDA 35mm at 550rpm per barrel. Effective ceiling 3000m.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'PTRD41', name: 'PTRD-41 Anti-Tank Rifle (14.5mm)', damage: 200,
      fireRate: 2.2, clipSize: 1, maxReserve: 20, reloadTime: 3.0,
      spread: 0.004, auto: false, type: 'SNIPER', hasScope: false, recoilY: 0.060, recoilX: 0.020,
      description: 'Soviet PTRD-41 semi-auto 14.5×114mm anti-tank rifle designed in 1941. Still filmed in Ukraine 2022-2025 — both sides unboxed WWII-era reserves. Devastating against unarmoured vehicles, engine blocks, crew-served weapons, and body armour at 500m+.',
    },
    {
      id: 'KONKURS', name: '9M113 Konkurs ATGM', damage: 780,
      fireRate: 5.0, clipSize: 1, maxReserve: 4, reloadTime: 6.5,
      spread: 0, auto: false, type: 'ATGM', recoilY: 0.042, recoilX: 0.012,
      blastRadius: 6, homing: true, hasScope: true,
      description: 'Soviet 9M113 Konkurs (AT-5 Spandrel) ATGM. Semi-automatic SACLOS wire-guided missile mounted on BMP-1P, BMP-2, and Konkurs-M vehicle mounts. One of the most common ATGMs in the Russian arsenal. Tandem warhead variant penetrates 750mm RHA behind ERA.',
    },
    {
      id: 'M32MGL', name: 'M32A1 MGL (6-shot Grenade Launcher)', damage: 195,
      fireRate: 1.2, clipSize: 6, maxReserve: 24, reloadTime: 6.0,
      spread: 0.025, auto: false, type: 'GRENADE', recoilY: 0.028, recoilX: 0.010,
      blastRadius: 5.5,
      description: 'Milkor M32A1 multi-shot 40mm grenade launcher. US supplied to Ukraine for fire support. Revolver-action fires 6 rounds of 40×46mm HE, smoke, or illumination in rapid succession. Range 350m point target, 800m area. Used by Ukrainian TDF rapid reaction units.',
    },
    {
      id: 'PPSH41', name: 'PPSh-41 (7.62mm Submachine Gun)', damage: 22,
      fireRate: 0.050, clipSize: 71, maxReserve: 213, reloadTime: 4.0,
      spread: 0.040, auto: true, type: 'SMG', recoilY: 0.020, recoilX: 0.009,
      description: 'Soviet PPSh-41 submachine gun. Iconic WWII weapon filmed in combat in Ukraine in 2022-2024. Both sides drew from 80-year-old arsenal reserves in the equipment shortages of early 2022. 71-round drum at 900rpm — terrifying in close quarters despite its age.',
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'AIAX', name: 'AI AXMC .338 Lapua Precision Rifle', damage: 210,
      fireRate: 1.2, clipSize: 10, maxReserve: 30, reloadTime: 5.0,
      spread: 0.002, auto: false, type: 'SNIPER', hasScope: true, recoilY: 0.048, recoilX: 0.014,
      description: 'Accuracy International AXMC multi-calibre chassis rifle in .338 Lapua Magnum. British precision rifle used by Ukrainian snipers including the famous "UA Ghost" team. Effective range 1400m. Modular system allows calibre change in the field between 7.62mm, .308, and .338.',
    },
    {
      id: 'MALYUTKA', name: '9M14 Malyutka (AT-3 Sagger) ATGM', damage: 500,
      fireRate: 7.0, clipSize: 1, maxReserve: 3, reloadTime: 8.0,
      spread: 0, auto: false, type: 'ATGM', recoilY: 0.030, recoilX: 0.008,
      blastRadius: 5, homing: true, hasScope: true,
      description: 'Soviet 9M14 Malyutka (AT-3 Sagger) — first mass-produced ATGM, from 1960. Manually guided via joystick. Both sides used thousands from ageing reserves. Famously used to devastating effect in the 1973 Arab-Israeli War. Still lethal against older armour in Ukraine.',
    },
    {
      id: 'VERBA', name: '9K333 Verba MANPADS', damage: 560,
      fireRate: 4.5, clipSize: 1, maxReserve: 3, reloadTime: 5.5,
      spread: 0, auto: false, type: 'AA', recoilY: 0.038, recoilX: 0.010,
      blastRadius: 4, homing: true, hasScope: true,
      description: "Russian 9K333 Verba (Willow) MANPADS. Russia's newest surface-to-air missile system as of 2022. Three-channel seeker (UV + near-IR + mid-IR) defeats all known flare countermeasures. Issued to Russian AA units and some special forces. Captured examples analyzed by Western intelligence.",
    },
    {
      id: 'RGN86', name: 'RGN-86 Offensive Grenade', damage: 175,
      fireRate: 1.8, clipSize: 3, maxReserve: 9, reloadTime: 1.5,
      spread: 0, auto: false, type: 'GRENADE', recoilY: 0.010, recoilX: 0.003,
      blastRadius: 5,
      description: "Russian RGN-86 offensive fragmentation grenade. Plastic body with shrapnel liner, fitted with UDZ impact-inertial fuze — detonates on impact OR after 3.2-4 seconds. Standard companion to RGO-78 defensive grenade. Both found throughout abandoned Russian positions around Kyiv in March 2022.",
    },
    // ── 4 more authentic war weapons ─────────────────────────────
    {
      id: 'RPG32', name: 'RPG-32 Hashim (reusable AT launcher)', damage: 580,
      fireRate: 4.0, clipSize: 1, maxReserve: 3, reloadTime: 5.2,
      spread: 0.007, auto: false, type: 'AT_LIGHT', recoilY: 0.068, recoilX: 0.022,
      blastRadius: 4.8,
      description: 'Russian/Jordanian RPG-32 Hashim. Reusable launcher body with interchangeable 72.5mm or 105mm warhead modules — unlike most single-use RPGs. Tandem warhead defeats ERA. Adopted by Russia and Jordan 2012; used in Ukraine by Russian forces and shared with allied groups.',
    },
    {
      id: 'G36C', name: 'HK G36C (5.56mm NATO)', damage: 28,
      fireRate: 0.082, clipSize: 30, maxReserve: 120, reloadTime: 2.1,
      spread: 0.016, auto: true, type: 'RIFLE', recoilY: 0.020, recoilX: 0.007,
      description: 'Heckler & Koch G36C compact carbine. Germany supplied G36 variants to Ukraine as part of aid packages from Bundeswehr stocks. Gas-operated rotating bolt, distinctive transparent magazine. Used alongside STANAG-standard firearms by Ukrainian special operations forces.',
    },
    {
      id: 'VASILEK', name: '2B9 Vasilek (82mm Auto Mortar)', damage: 700,
      fireRate: 2.8, clipSize: 4, maxReserve: 20, reloadTime: 6.0,
      spread: 0.015, auto: false, type: 'EXPLOSIVE', recoilY: 0.015, recoilX: 0.005,
      blastRadius: 9,
      description: 'Soviet 2B9 Vasilek automatic 82mm mortar. Semi-auto feed via 4-round clips at 100rpm max. Can fire like artillery in flat-trajectory direct fire mode (unique among mortars). Both sides use from ageing stocks. Tripod + wheeled carriage — visible at dug-in positions throughout the Donbas.',
    },
    {
      id: 'B10', name: 'B-10 Recoilless Rifle (82mm)', damage: 420,
      fireRate: 3.5, clipSize: 1, maxReserve: 5, reloadTime: 5.0,
      spread: 0.010, auto: false, type: 'AT', recoilY: 0.055, recoilX: 0.015,
      blastRadius: 5,
      description: 'Soviet B-10 82mm recoilless rifle from 1954. Smooth-bore with breech counterblast. Both sides dug B-10s from 60-year-old arsenals during 2022 equipment shortages. Shoulder-fired or wheel-carriage mounted. Still effective against APCs and fortified positions at 400m.',
    },
    {
      id: 'AK74M', name: 'AK-74M (5.45×39mm)', damage: 26,
      fireRate: 0.079, clipSize: 30, maxReserve: 120, reloadTime: 2.0,
      spread: 0.014, auto: true, type: 'RIFLE', recoilY: 0.017, recoilX: 0.005,
      description: "Russia's standard-issue service rifle since 1991. 5.45mm intermediate cartridge, side-folding polymer stock, muzzle brake that nearly eliminates climb. The AK-74M is carried by virtually every Russian soldier in Ukraine — the most common opposing weapon on the battlefield.",
    },
    {
      id: 'SWITCHBLADE600', name: 'Switchblade 600 (anti-armor loitering munition)', damage: 680,
      fireRate: 5.0, clipSize: 1, maxReserve: 2, reloadTime: 8.0,
      spread: 0.003, auto: false, type: 'AT_LIGHT', recoilY: 0.005, recoilX: 0.001,
      homing: true, blastRadius: 6,
      description: "AeroVironment Switchblade 600 — US-supplied anti-armor kamikaze drone. Much larger than the 300 variant, purpose-built to defeat armored vehicles. Deploys from a tube, wings unfold mid-air, operator guides to target via live video feed. Warhead equivalent to a Javelin. Provided to Ukraine under US military aid packages from 2022.",
    },
    {
      id: 'PZH2000', name: 'Panzerhaubitze 2000 (155mm SPH)', damage: 1200,
      fireRate: 6.0, clipSize: 3, maxReserve: 9, reloadTime: 9.0,
      spread: 0.012, auto: false, type: 'EXPLOSIVE', recoilY: 0.010, recoilX: 0.003,
      blastRadius: 14,
      description: "German/Dutch PzH 2000 self-propelled howitzer. 155mm/L52 barrel with autoloader — 3 rounds in under 10 seconds. Germany and Netherlands donated ~20 units to Ukraine in 2022; proved devastating against Russian logistics and troop concentrations. Max range 40km with base bleed ammunition.",
    },
    {
      id: 'KH101', name: 'Kh-101 Cruise Missile', damage: 2400,
      fireRate: 0.0, clipSize: 1, maxReserve: 1, reloadTime: 12.0,
      spread: 0.002, auto: false, type: 'AT_HEAVY', recoilY: 0.0, recoilX: 0.0,
      homing: true, blastRadius: 22,
      description: "Russian Kh-101 air-launched cruise missile. Stealthy composite airframe, terrain-following guidance, 400kg warhead. Russia fires these from Tu-95MS and Tu-160 bombers targeting Ukrainian cities, power grid, and infrastructure. Ukraine intercepts ~50% with Patriots and F-16s, but mass salvos overwhelm defences. Range 5,000km.",
    },
    {
      id: 'CAESAR155', name: 'CAESAR 155mm SPH (Call Fire)', damage: 1100,
      fireRate: 5.0, clipSize: 2, maxReserve: 6, reloadTime: 8.0,
      spread: 0.010, auto: false, type: 'EXPLOSIVE', recoilY: 0.010, recoilX: 0.002,
      blastRadius: 13,
      description: "French CAESAR (CAmion Équipé d'un Système d'ARtillerie) 155mm/L52 self-propelled howitzer mounted on a 6×6 truck. France donated 18 to Ukraine in 2022 — their wheeled design allows 80km/h road speed, shoot-and-scoot in under 90 seconds. Range 42km with Excalibur GPS rounds. Proved devastating against Russian command posts and logistics.",
    },
    {
      id: 'BRIMSTONE2', name: 'Brimstone 2 (UK Precision ATGM)', damage: 380,
      fireRate: 2.5, clipSize: 3, maxReserve: 9, reloadTime: 6.0,
      spread: 0.003, auto: false, type: 'AT_LIGHT', recoilY: 0.005, recoilX: 0.001,
      homing: true, blastRadius: 5,
      description: "MBDA Brimstone 2 — British precision anti-armor missile with dual-mode millimetre-wave radar and semi-active laser homing. UK donated Brimstones to Ukraine in 2022. Highly accurate against moving armored vehicles; can be ripple-fired in salvo to defeat multiple targets simultaneously. Tandem HEAT warhead defeats ERA. Range 12km air-launched.",
    },
    {
      id: 'IRISTSLM', name: 'IRIS-T SLM (German Air Defense)', damage: 600,
      fireRate: 3.0, clipSize: 4, maxReserve: 8, reloadTime: 7.0,
      spread: 0.003, auto: false, type: 'AT_HEAVY', recoilY: 0.006, recoilX: 0.001,
      homing: true, blastRadius: 8,
      description: "Diehl Defence IRIS-T SLM (Surface Launched Medium range) — Germany delivered the first system to Ukraine in October 2022. Fires IRIS-T missiles at up to 40km range and 20km altitude, defeating drones, cruise missiles, and aircraft. Claimed ~96% intercept rate against Shahed drones. Each system can simultaneously engage multiple targets with active radar seekers.",
    },
    {
      id: 'ATACMS', name: 'MGM-140 ATACMS (US Ballistic Missile)', damage: 1800,
      fireRate: 0.0, clipSize: 1, maxReserve: 2, reloadTime: 12.0,
      spread: 0.002, auto: false, type: 'EXPLOSIVE', recoilY: 0.0, recoilX: 0.0,
      homing: true, blastRadius: 18,
      description: "US Army Tactical Missile System — fires from standard HIMARS or M270 MLRS launchers. Ukraine secretly received ATACMS in late 2023; used them to strike Russian air bases in Crimea and Berdyansk port (sank landing ships). M39 variant carries 950 M74 submunitions; M57 variant has 227kg unitary warhead. Range 300km — reaches deep into Russian-controlled territory.",
    },
  ];
  return { WEAPONS: WEAPONS };
})();
if (typeof window !== 'undefined') window.WeaponData = WeaponData;
