window.BoneKeep = (function() {
    'use strict';
    var scene = null;
    var camera = null;
    var objects = [];
    var lights = [];
    function init(sceneRef, cameraRef) {
        scene = sceneRef; camera = cameraRef;
        objects = []; lights = [];
        buildKeep();
    }
    function buildKeep() {
        var boneWhite = 0xf5f5dc;
        var darkBone = 0xa9a9a9;
        var blackBone = 0x1a1a1a;
        var dullBone = 0xc9c9a8;
        var towerGeom = new THREE.BoxGeometry(8, 20, 8);
        var towerMat = new THREE.MeshLambertMaterial({color: boneWhite});
        var tower1 = new THREE.Mesh(towerGeom, towerMat);
        tower1.position.set(-25, 10, -25);
        tower1.castShadow = true;
        tower1.receiveShadow = true;
        scene.add(tower1);
        objects.push(tower1);
        var tower2 = new THREE.Mesh(towerGeom, towerMat);
        tower2.position.set(25, 10, -25);
        tower2.castShadow = true;
        tower2.receiveShadow = true;
        scene.add(tower2);
        objects.push(tower2);
        var tower3 = new THREE.Mesh(towerGeom, towerMat);
        tower3.position.set(-25, 10, 25);
        tower3.castShadow = true;
        tower3.receiveShadow = true;
        scene.add(tower3);
        objects.push(tower3);
        var tower4 = new THREE.Mesh(towerGeom, towerMat);
        tower4.position.set(25, 10, 25);
        tower4.castShadow = true;
        tower4.receiveShadow = true;
        scene.add(tower4);
        objects.push(tower4);
        var boneArchGeom = new THREE.CylinderGeometry(1.5, 1.5, 6, 8);
        var boneMat = new THREE.MeshLambertMaterial({color: darkBone});
        var boneArch1 = new THREE.Mesh(boneArchGeom, boneMat);
        boneArch1.position.set(-15, 12, -30);
        boneArch1.rotation.z = Math.PI / 2;
        boneArch1.castShadow = true;
        scene.add(boneArch1);
        objects.push(boneArch1);
        var boneArch2 = new THREE.Mesh(boneArchGeom, boneMat);
        boneArch2.position.set(15, 12, -30);
        boneArch2.rotation.z = Math.PI / 2;
        boneArch2.castShadow = true;
        scene.add(boneArch2);
        objects.push(boneArch2);
        var skullGeom = new THREE.SphereGeometry(2, 16, 16);
        var skullMat = new THREE.MeshLambertMaterial({color: 0xfffaf0});
        var skull1 = new THREE.Mesh(skullGeom, skullMat);
        skull1.position.set(-20, 18, -20);
        skull1.scale.set(1, 1.2, 0.9);
        skull1.castShadow = true;
        scene.add(skull1);
        objects.push(skull1);
        var skull2 = new THREE.Mesh(skullGeom, skullMat);
        skull2.position.set(20, 18, 20);
        skull2.scale.set(1, 1.2, 0.9);
        skull2.castShadow = true;
        scene.add(skull2);
        objects.push(skull2);
        var skullSmallGeom = new THREE.SphereGeometry(1, 12, 12);
        var skullSmall1 = new THREE.Mesh(skullSmallGeom, skullMat);
        skullSmall1.position.set(-22, 16, -22);
        skullSmall1.castShadow = true;
        scene.add(skullSmall1);
        objects.push(skullSmall1);
        var skullSmall2 = new THREE.Mesh(skullSmallGeom, skullMat);
        skullSmall2.position.set(22, 16, 22);
        skullSmall2.castShadow = true;
        scene.add(skullSmall2);
        objects.push(skullSmall2);
        var catacombGeom = new THREE.ConeGeometry(6, 8, 16);
        var cataMAT = new THREE.MeshLambertMaterial({color: blackBone});
        var catacomb = new THREE.Mesh(catacombGeom, cataMAT);
        catacomb.position.set(0, 4, 0);
        catacomb.castShadow = true;
        catacomb.receiveShadow = true;
        scene.add(catacomb);
        objects.push(catacomb);
        var courtGeom = new THREE.BoxGeometry(35, 1, 35);
        var courtMat = new THREE.MeshLambertMaterial({color: dullBone});
        var courtyard = new THREE.Mesh(courtGeom, courtMat);
        courtyard.position.set(0, -0.5, 0);
        courtyard.receiveShadow = true;
        scene.add(courtyard);
        objects.push(courtyard);
        var smallSkull = new THREE.Mesh(skullSmallGeom, skullMat);
        smallSkull.position.set(-10, 1, 10);
        smallSkull.castShadow = true;
        scene.add(smallSkull);
        objects.push(smallSkull);
        var smallSkull2 = new THREE.Mesh(skullSmallGeom, skullMat);
        smallSkull2.position.set(10, 1, -10);
        smallSkull2.castShadow = true;
        scene.add(smallSkull2);
        objects.push(smallSkull2);
        var smallSkull3 = new THREE.Mesh(skullSmallGeom, skullMat);
        smallSkull3.position.set(0, 1, 15);
        smallSkull3.castShadow = true;
        scene.add(smallSkull3);
        objects.push(smallSkull3);
        var bonePost = new THREE.Mesh(boneArchGeom, boneMat);
        bonePost.position.set(-8, 8, 0);
        bonePost.scale.set(1, 2, 1);
        bonePost.castShadow = true;
        scene.add(bonePost);
        objects.push(bonePost);
        var bonePost2 = new THREE.Mesh(boneArchGeom, boneMat);
        bonePost2.position.set(8, 8, 0);
        bonePost2.scale.set(1, 2, 1);
        bonePost2.castShadow = true;
        scene.add(bonePost2);
        objects.push(bonePost2);
        var ambientLight = new THREE.AmbientLight(0xffffff, 0.4);
        scene.add(ambientLight);
        lights.push(ambientLight);
        var directionalLight = new THREE.DirectionalLight(0xffffff, 0.8);
        directionalLight.position.set(20, 30, 20);
        directionalLight.castShadow = true;
        directionalLight.shadow.mapSize.width = 2048;
        directionalLight.shadow.mapSize.height = 2048;
        directionalLight.shadow.camera.far = 100;
        directionalLight.shadow.camera.left = -50;
        directionalLight.shadow.camera.right = 50;
        directionalLight.shadow.camera.top = 50;
        directionalLight.shadow.camera.bottom = -50;
        scene.add(directionalLight);
        lights.push(directionalLight);
    }
    function update(delta) {
        for (var i = 0; i < objects.length; i++) {
            if (objects[i].rotation) {
                objects[i].rotation.y += delta * 0.05;
            }
        }
    }
    function reset() {
        for (var i = 0; i < objects.length; i++) scene.remove(objects[i]);
        for (var i = 0; i < lights.length; i++) scene.remove(lights[i]);
        objects = [];
        lights = [];
        scene = null;
        camera = null;
    }
    return { init: init, update: update, reset: reset };
}());
