// mortar-deploy.js — Player-deployable mortar with FDC top-down fire mode
// Deploy key: F12 (verified free: F1-F7=build, F8=C4, F9=settings, F10=FPS, F11=browser)
window.MortarDeploy = (function () {
  'use strict';
  var DEPLOY_KEY='F12',SETUP_TIME=3,PACK_TIME=2,FLIGHT_TIME=3,BLAST_RADIUS=8,SHELL_DAMAGE=80,FIRE_COOLDOWN=6,MAX_AMMO=5,MORTAR_HP=80,FDC_CAM_Y=25,FDC_CAM_LOOK_Y=0,RANGE_RING_RADII=[10,20,30,40];
  var _scene=null,_camera=null,_renderer=null,_state='idle',_setupTimer=0,_packTimer=0,_fireCooldown=0,_ammo=MAX_AMMO,_hp=MORTAR_HP,_mortarPos=null,_mortarGroup=null,_tubemesh=null,_baseplate=null,_bipod1=null,_bipod2=null,_rangeRings=[],_savedCamPos=null,_savedCamTarget=null,_shells=[],_fdcHud=null,_fdcAmmoEl=null,_fdcWindEl=null,_fdcGridCanvas=null,_fdcFireLabel=null,_groundPlane=null,_cursorMesh=null,_previewDots=[],_mouse={x:0,y:0},_fdcTarget=null,_audioCtx=null,_keyDown={},_boundKeyDown=null,_boundKeyUp=null,_boundMouseMove=null,_boundClick=null;
  window._mortarDeployed=false;window._mortarShells=0;
  function _getThree(){return(typeof window!=='undefined'&&window.THREE)?window.THREE:null;}
  function _makeMat(c){var T=_getThree();if(!T)return null;return new T.MeshLambertMaterial({color:c});}
  function _ensureAudio(){if(_audioCtx)return _audioCtx;try{_audioCtx=new(window.AudioContext||window.webkitAudioContext)();}catch(e){_audioCtx=null;}return _audioCtx;}
  function _playThunk(){var ctx=_ensureAudio();if(!ctx)return;var osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(60,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(25,ctx.currentTime+0.2);gain.gain.setValueAtTime(0.9,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+0.2);osc.connect(gain);gain.connect(ctx.destination);osc.start(ctx.currentTime);osc.stop(ctx.currentTime+0.2);}
  function _playBoom(){var ctx=_ensureAudio();if(!ctx)return;var buf=ctx.createBuffer(1,Math.floor(ctx.sampleRate*0.6),ctx.sampleRate),data=buf.getChannelData(0);for(var i=0;i<data.length;i++){data[i]=(Math.random()*2-1)*Math.exp(-i/(ctx.sampleRate*0.12));}var src=ctx.createBufferSource(),filt=ctx.createBiquadFilter(),gain=ctx.createGain();src.buffer=buf;filt.type='lowpass';filt.frequency.value=180;gain.gain.setValueAtTime(1.5,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+0.6);src.connect(filt);filt.connect(gain);gain.connect(ctx.destination);src.start(ctx.currentTime);var osc=ctx.createOscillator(),og=ctx.createGain();osc.type='sine';osc.frequency.value=45;og.gain.setValueAtTime(0.8,ctx.currentTime);og.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+0.5);osc.connect(og);og.connect(ctx.destination);osc.start(ctx.currentTime);osc.stop(ctx.currentTime+0.5);}
  function _buildMortarMesh(){var T=_getThree();if(!T||!_scene)return;_mortarGroup=new T.Group();var tubeGeo=new T.CylinderGeometry(0.12,0.15,0.6,10),tubeMat=_makeMat(0x3A3A3A);_tubemesh=new T.Mesh(tubeGeo,tubeMat);_tubemesh.rotation.x=Math.PI*(60/180);_tubemesh.position.set(0,0.5,0);_mortarGroup.add(_tubemesh);var baseGeo=new T.BoxGeometry(0.5,0.06,0.5),baseMat=_makeMat(0x2A2A2A);_baseplate=new T.Mesh(baseGeo,baseMat);_baseplate.position.set(0,0.03,0);_mortarGroup.add(_baseplate);var legGeo=new T.CylinderGeometry(0.03,0.03,0.6,6),legMat=_makeMat(0x333333);_bipod1=new T.Mesh(legGeo,legMat);_bipod1.rotation.z=Math.PI/6;_bipod1.position.set(0.18,0.25,0.05);_mortarGroup.add(_bipod1);_bipod2=new T.Mesh(legGeo.clone(),legMat.clone());_bipod2.rotation.z=-Math.PI/6;_bipod2.position.set(-0.18,0.25,0.05);_mortarGroup.add(_bipod2);_mortarGroup.visible=false;_scene.add(_mortarGroup);}
  function _buildRangeRings(){var T=_getThree();if(!T||!_scene)return;_rangeRings=[];for(var i=0;i<RANGE_RING_RADII.length;i++){var r=RANGE_RING_RADII[i],pts=[],j,ang;for(j=0;j<=64;j++){ang=(j/64)*Math.PI*2;pts.push(new T.Vector3(Math.cos(ang)*r,0.05,Math.sin(ang)*r));}var geo=new T.BufferGeometry().setFromPoints(pts),mat=new T.LineBasicMaterial({color:0x00ff88,opacity:0.35,transparent:true}),ring=new T.Line(geo,mat);ring.visible=false;_scene.add(ring);_rangeRings.push(ring);}}
  function _buildGroundCursor(){var T=_getThree();if(!T||!_scene)return;var pgeo=new T.PlaneGeometry(2000,2000),pmat=new T.MeshBasicMaterial({visible:false,side:T.DoubleSide});_groundPlane=new T.Mesh(pgeo,pmat);_groundPlane.rotation.x=-Math.PI/2;_groundPlane.visible=false;_scene.add(_groundPlane);var cpts=[],k,a;for(k=0;k<=32;k++){a=(k/32)*Math.PI*2;cpts.push(new T.Vector3(Math.cos(a),0,Math.sin(a)));}var cgeo=new T.BufferGeometry().setFromPoints(cpts),cmat=new T.LineBasicMaterial({color:0xff4400,opacity:0.85,transparent:true});_cursorMesh=new T.Line(cgeo,cmat);_cursorMesh.visible=false;_scene.add(_cursorMesh);_previewDots=[];for(var d=0;d<3;d++){var dotGeo=new T.SphereGeometry(0.2,6,6),dotMat=new T.MeshBasicMaterial({color:0xffaa00,transparent:true,opacity:0.7}),dot=new T.Mesh(dotGeo,dotMat);dot.visible=false;_scene.add(dot);_previewDots.push(dot);}}
  function _buildFDCHud(){if(_fdcHud)return;_fdcHud=document.createElement('div');_fdcHud.id='mortar-fdc-hud';_fdcHud.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;pointer-events:none;z-index:290;display:none;font-family:monospace';_fdcGridCanvas=document.createElement('canvas');_fdcGridCanvas.style.cssText='position:absolute;top:0;left:0;width:100%;height:100%;opacity:0.12;pointer-events:none;';_fdcHud.appendChild(_fdcGridCanvas);_fdcFireLabel=document.createElement('div');_fdcFireLabel.style.cssText='position:absolute;top:16px;left:50%;transform:translateX(-50%);color:#ff4400;font-size:18px;font-weight:bold;letter-spacing:4px;text-shadow:0 0 12px rgba(255,68,0,0.8);pointer-events:none';_fdcFireLabel.textContent='FIRE FOR EFFECT';_fdcHud.appendChild(_fdcFireLabel);_fdcAmmoEl=document.createElement('div');_fdcAmmoEl.style.cssText='position:absolute;bottom:60px;left:50%;transform:translateX(-50%);color:#ffcc00;font-size:16px;letter-spacing:2px;text-shadow:0 0 8px rgba(255,200,0,0.6);pointer-events:none';_fdcHud.appendChild(_fdcAmmoEl);_fdcWindEl=document.createElement('div');_fdcWindEl.style.cssText='position:absolute;top:16px;right:24px;color:#88ddff;font-size:12px;letter-spacing:1px;pointer-events:none';_fdcWindEl.innerHTML='WIND: '+_randWindStr();_fdcHud.appendChild(_fdcWindEl);var statusEl=document.createElement('div');statusEl.id='mortar-fdc-status';statusEl.style.cssText='position:absolute;bottom:30px;left:50%;transform:translateX(-50%);color:#aaa;font-size:11px;letter-spacing:1px;pointer-events:none';statusEl.textContent='LMB: FIRE  |  '+DEPLOY_KEY+': PACK UP';_fdcHud.appendChild(statusEl);document.body.appendChild(_fdcHud);_drawFDCGrid();}
  function _randWindStr(){var dirs=['N','NE','E','SE','S','SW','W','NW'],spd=Math.round(Math.random()*12+2),dir=dirs[Math.floor(Math.random()*dirs.length)];return spd+' kts '+dir;}
  function _drawFDCGrid(){if(!_fdcGridCanvas)return;var W=window.innerWidth,H=window.innerHeight,x,y;_fdcGridCanvas.width=W;_fdcGridCanvas.height=H;var ctx=_fdcGridCanvas.getContext('2d');ctx.clearRect(0,0,W,H);ctx.strokeStyle='#00ff88';ctx.lineWidth=1;var step=60;ctx.beginPath();for(x=0;x<W;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,H);}for(y=0;y<H;y+=step){ctx.moveTo(0,y);ctx.lineTo(W,y);}ctx.stroke();}
  function _updateAmmoHud(){if(!_fdcAmmoEl)return;var squares='';for(var i=0;i<MAX_AMMO;i++){squares+=(i<_ammo)?'▪':'▫';}_fdcAmmoEl.textContent='AMMO: '+squares;}
  function _showFDCHud(visible){if(!_fdcHud)_buildFDCHud();_fdcHud.style.display=visible?'block':'none';if(visible){_updateAmmoHud();_drawFDCGrid();}}
  function _enterFDC(){if(!_camera||!_mortarPos)return;var T=_getThree();if(!T)return;_savedCamPos=_camera.position.clone();_savedCamTarget=_camera.getWorldDirection(new T.Vector3());_camera.position.set(_mortarPos.x,_mortarPos.y+FDC_CAM_Y,_mortarPos.z);_camera.lookAt(new T.Vector3(_mortarPos.x,FDC_CAM_LOOK_Y,_mortarPos.z));if(_camera.updateProjectionMatrix)_camera.updateProjectionMatrix();for(var i=0;i<_rangeRings.length;i++){_rangeRings[i].position.set(_mortarPos.x,0.05,_mortarPos.z);_rangeRings[i].visible=true;}if(_groundPlane)_groundPlane.visible=true;if(_cursorMesh)_cursorMesh.visible=true;_showFDCHud(true);_state='fdc';window._mortarDeployed=true;}
  function _exitFDC(restore){_showFDCHud(false);for(var i=0;i<_rangeRings.length;i++){_rangeRings[i].visible=false;}if(_groundPlane)_groundPlane.visible=false;if(_cursorMesh)_cursorMesh.visible=false;for(var j=0;j<_previewDots.length;j++){_previewDots[j].visible=false;}if(restore&&_camera&&_savedCamPos){_camera.position.copy(_savedCamPos);_savedCamPos=null;}}
  function _spawnShell(target){var T=_getThree();if(!T||!_scene||!_mortarPos)return;var origin=_mortarPos.clone().add(new T.Vector3(0,0.8,0)),geo=new T.SphereGeometry(0.12,6,6),mat=new T.MeshBasicMaterial({color:0x333333}),mesh=new T.Mesh(geo,mat);mesh.position.copy(origin);_scene.add(mesh);_shells.push({mesh:mesh,t:0,origin:origin.clone(),target:target.clone()});}
  function _updateShells(dt){var i,j,s,toRemove=[];for(i=0;i<_shells.length;i++){s=_shells[i];s.t+=dt/FLIGHT_TIME;if(s.t>=1){_onImpact(s.target);if(_scene)_scene.remove(s.mesh);toRemove.push(i);continue;}var t=s.t,px=s.origin.x+(s.target.x-s.origin.x)*t,pz=s.origin.z+(s.target.z-s.origin.z)*t,py=s.origin.y+(s.target.y-s.origin.y)*t+18*t*(1-t);s.mesh.position.set(px,py,pz);}for(j=toRemove.length-1;j>=0;j--){_shells.splice(toRemove[j],1);}}
  function _onImpact(pos){_playBoom();_spawnExplosionVFX(pos);_damageEnemiesInRadius(pos,BLAST_RADIUS,SHELL_DAMAGE);if(window.HUD&&window.HUD.showToast)window.HUD.showToast('IMPACT!',800,'#ff4400');}
  function _spawnExplosionVFX(pos){var T=_getThree();if(!T||!_scene)return;var geo=new T.SphereGeometry(1,8,8),mat=new T.MeshBasicMaterial({color:0xff6600,transparent:true,opacity:0.9}),ball=new T.Mesh(geo,mat);ball.position.copy(pos);_scene.add(ball);var particles=[],i;for(i=0;i<12;i++){var pg=new T.SphereGeometry(0.15,4,4),pm=new T.MeshBasicMaterial({color:0x553300}),pm2=new T.Mesh(pg,pm);pm2.position.copy(pos);particles.push({mesh:pm2,vx:(Math.random()-0.5)*14,vy:Math.random()*8+4,vz:(Math.random()-0.5)*14,life:0,lastT:0});_scene.add(pm2);}var startTime=null,DURATION=0.8,scn=_scene;function animateExplosion(ts){if(!startTime)startTime=ts;var elapsed=(ts-startTime)/1000,frac=Math.min(elapsed/DURATION,1);ball.scale.setScalar(1+frac*(BLAST_RADIUS*0.8));ball.material.opacity=0.9*(1-frac);var k,p,dT;for(k=0;k<particles.length;k++){p=particles[k];dT=elapsed-p.lastT;p.lastT=elapsed;p.life+=dT;p.mesh.position.x+=p.vx*dT;p.mesh.position.y+=(p.vy-9.8*p.life)*dT;p.mesh.position.z+=p.vz*dT;}if(frac<1){requestAnimationFrame(animateExplosion);}else{scn.remove(ball);for(var m=0;m<particles.length;m++)scn.remove(particles[m].mesh);}}requestAnimationFrame(animateExplosion);}
  function _damageEnemiesInRadius(pos,radius,dmg){var enemies=(window.Enemies&&window.Enemies._enemies)||(window.GameManager&&window.GameManager.enemies)||[];for(var i=0;i<enemies.length;i++){var e=enemies[i];if(!e||!e.mesh)continue;var dist=e.mesh.position.distanceTo(pos);if(dist<=radius){var scale=1-(dist/radius)*0.5,actualDmg=Math.round(dmg*scale);if(e.takeDamage)e.takeDamage(actualDmg,'mortar');else if(e.hp!==undefined){e.hp-=actualDmg;}}}}
  function _updateSetupAnim(dt){if(_state!=='setup')return;_setupTimer+=dt;var frac=Math.min(_setupTimer/SETUP_TIME,1);if(_tubemesh){_tubemesh.rotation.x=Math.PI*(60/180)*frac;_tubemesh.scale.setScalar(frac);}if(_bipod1)_bipod1.scale.setScalar(frac);if(_bipod2)_bipod2.scale.setScalar(frac);if(_setupTimer>=SETUP_TIME){_state='ready';if(window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR READY — '+DEPLOY_KEY+' for FDC',2500,'#ffcc00');_enterFDC();}}
  function _updatePackAnim(dt){if(_state!=='packing')return;_packTimer+=dt;var frac=1-Math.min(_packTimer/PACK_TIME,1);if(_tubemesh){_tubemesh.rotation.x=Math.PI*(60/180)*frac;_tubemesh.scale.setScalar(frac);}if(_bipod1)_bipod1.scale.setScalar(frac);if(_bipod2)_bipod2.scale.setScalar(frac);if(_packTimer>=PACK_TIME){if(_mortarGroup)_mortarGroup.visible=false;_exitFDC(true);_state='idle';window._mortarDeployed=false;window._mortarShells=0;if(window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR PACKED',2000,'#aaa');}}
  function _updateFDCCursor(){if(_state!=='fdc'||!_camera||!_renderer)return;var T=_getThree();if(!T||!_groundPlane)return;var raycaster=new T.Raycaster(),mouseVec=new T.Vector2(_mouse.x,_mouse.y);raycaster.setFromCamera(mouseVec,_camera);var hits=raycaster.intersectObject(_groundPlane);if(hits.length>0){_fdcTarget=hits[0].point.clone();if(_cursorMesh)_cursorMesh.position.set(_fdcTarget.x,0.1,_fdcTarget.z);_updatePreviewDots(_fdcTarget);}}
  function _updatePreviewDots(target){var T=_getThree();if(!T||!_mortarPos)return;var fracs=[0.25,0.5,0.75],origin=_mortarPos.clone().add(new T.Vector3(0,0.8,0));for(var i=0;i<fracs.length;i++){var t=fracs[i],px=origin.x+(target.x-origin.x)*t,pz=origin.z+(target.z-origin.z)*t,py=origin.y+(target.y-origin.y)*t+18*t*(1-t);if(_previewDots[i]){_previewDots[i].position.set(px,py,pz);_previewDots[i].visible=true;}}}
  function _onKeyDown(e){_keyDown[e.code]=true;if(e.code===DEPLOY_KEY){e.preventDefault();if(_state==='idle'){var pp=_getPlayerPos();if(pp){deploy(pp);}else if(window.HUD&&window.HUD.showToast){window.HUD.showToast('No player position — cannot deploy',1500,'#ff4444');}}else if(_state==='fdc'||_state==='ready'){pack();}}}
  function _onKeyUp(e){_keyDown[e.code]=false;}
  function _onMouseMove(e){_mouse.x=(e.clientX/window.innerWidth)*2-1;_mouse.y=-(e.clientY/window.innerHeight)*2+1;}
  function _onClickFDC(e){if(_state!=='fdc')return;if(e.button!==0)return;if(!_fdcTarget)return;if(_fireCooldown>0){if(window.HUD&&window.HUD.showToast)window.HUD.showToast('RELOADING…',800,'#aaa');return;}if(_ammo<=0){if(window.HUD&&window.HUD.showToast)window.HUD.showToast('NO AMMO',1200,'#ff4444');return;}fire(_fdcTarget.clone());}
  function _getPlayerPos(){if(window.GameManager&&window.GameManager.playerPos)return window.GameManager.playerPos;if(window._playerMesh&&window._playerMesh.position)return window._playerMesh.position;if(window.GameManager&&window.GameManager._player&&window.GameManager._player.position)return window.GameManager._player.position;return null;}
  function init(scene,camera,renderer){_scene=scene||(window.GameManager&&window.GameManager._scene)||null;_camera=camera||(window.GameManager&&window.GameManager._camera)||null;_renderer=renderer||(window.GameManager&&window.GameManager._renderer)||null;if(_scene){_buildMortarMesh();_buildRangeRings();_buildGroundCursor();}_buildFDCHud();_boundKeyDown=_onKeyDown;_boundKeyUp=_onKeyUp;_boundMouseMove=_onMouseMove;_boundClick=_onClickFDC;window.addEventListener('keydown',_boundKeyDown,true);window.addEventListener('keyup',_boundKeyUp,false);window.addEventListener('mousemove',_boundMouseMove,false);window.addEventListener('mousedown',_boundClick,false);var btn=document.getElementById('mortar-btn');if(btn){btn.addEventListener('click',function(){var pp=_getPlayerPos();if(_state==='idle'&&pp){deploy(pp);}else if(_state==='fdc'||_state==='ready'){pack();}});}console.log('[MortarDeploy] initialised — deploy key: '+DEPLOY_KEY);}
  function deploy(playerPos){if(_state!=='idle')return;var T=_getThree();if(!T){console.warn('[MortarDeploy] THREE not found');return;}_mortarPos=new T.Vector3(playerPos.x,playerPos.y,playerPos.z);_ammo=MAX_AMMO;_hp=MORTAR_HP;_setupTimer=0;window._mortarShells=_ammo;if(!_mortarGroup)_buildMortarMesh();if(_mortarGroup){_mortarGroup.position.copy(_mortarPos);_mortarGroup.visible=true;if(_tubemesh){_tubemesh.rotation.x=0;_tubemesh.scale.setScalar(0);}if(_bipod1)_bipod1.scale.setScalar(0);if(_bipod2)_bipod2.scale.setScalar(0);}_state='setup';window._mortarDeployed=true;if(window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR DEPLOYING… '+SETUP_TIME+'s',2800,'#ffaa66');}
  function fire(targetPos){if(_state!=='fdc')return;if(_ammo<=0)return;if(_fireCooldown>0)return;_playThunk();_spawnShell(targetPos);_ammo--;_fireCooldown=FIRE_COOLDOWN;window._mortarShells=_ammo;_updateAmmoHud();var statusEl=document.getElementById('mortar-fdc-status');if(statusEl)statusEl.textContent='RELOADING…  '+FIRE_COOLDOWN+'s';if(_ammo<=0&&window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR — AMMO DEPLETED',2500,'#ff4444');}
  function pack(){if(_state!=='fdc'&&_state!=='ready')return;_exitFDC(true);_state='packing';_packTimer=0;if(window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR PACKING…',2200,'#aaa');}
  function damage(amount){if(_state==='idle'||_state==='destroyed')return;_hp-=amount;if(_hp<=0){_hp=0;_state='destroyed';if(_mortarPos)_spawnExplosionVFX(_mortarPos);if(_mortarGroup)_mortarGroup.visible=false;_exitFDC(true);window._mortarDeployed=false;window._mortarShells=0;if(window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR DESTROYED!',2500,'#ff2222');}}
  function update(dt,camera,playerPos){if(camera)_camera=camera;if(!_scene&&window.GameManager){_scene=window.GameManager._scene||_scene;_camera=window.GameManager._camera||_camera;_renderer=window.GameManager._renderer||_renderer;if(_scene&&!_mortarGroup){_buildMortarMesh();_buildRangeRings();_buildGroundCursor();}}_updateSetupAnim(dt);_updatePackAnim(dt);_updateShells(dt);if(_state==='fdc'){_updateFDCCursor();if(_camera&&_mortarPos){var T=_getThree();if(T){_camera.position.set(_mortarPos.x,_mortarPos.y+FDC_CAM_Y,_mortarPos.z);_camera.lookAt(new T.Vector3(_mortarPos.x,FDC_CAM_LOOK_Y,_mortarPos.z));}}_fireCooldown=Math.max(0,_fireCooldown-dt);if(_fireCooldown===0){var statusEl=document.getElementById('mortar-fdc-status');if(statusEl)statusEl.textContent='LMB: FIRE  |  '+DEPLOY_KEY+': PACK UP';if(_ammo>0&&window.HUD&&window.HUD.showToast)window.HUD.showToast('MORTAR READY',1000,'#ffcc00');}}}
  function reset(){_exitFDC(true);var i;for(i=0;i<_shells.length;i++){if(_scene&&_shells[i].mesh)_scene.remove(_shells[i].mesh);}_shells=[];if(_scene&&_mortarGroup)_scene.remove(_mortarGroup);_mortarGroup=null;_tubemesh=null;_baseplate=null;_bipod1=null;_bipod2=null;for(i=0;i<_rangeRings.length;i++){if(_scene)_scene.remove(_rangeRings[i]);}_rangeRings=[];if(_scene&&_groundPlane)_scene.remove(_groundPlane);if(_scene&&_cursorMesh)_scene.remove(_cursorMesh);for(i=0;i<_previewDots.length;i++){if(_scene)_scene.remove(_previewDots[i]);}_previewDots=[];_groundPlane=null;_cursorMesh=null;if(_fdcHud&&_fdcHud.parentNode)_fdcHud.parentNode.removeChild(_fdcHud);_fdcHud=null;_fdcAmmoEl=null;_fdcWindEl=null;_fdcGridCanvas=null;_fdcFireLabel=null;if(_boundKeyDown)window.removeEventListener('keydown',_boundKeyDown,true);if(_boundKeyUp)window.removeEventListener('keyup',_boundKeyUp,false);if(_boundMouseMove)window.removeEventListener('mousemove',_boundMouseMove,false);if(_boundClick)window.removeEventListener('mousedown',_boundClick,false);_boundKeyDown=_boundKeyUp=_boundMouseMove=_boundClick=null;_state='idle';_ammo=MAX_AMMO;_hp=MORTAR_HP;_mortarPos=null;_savedCamPos=null;_savedCamTarget=null;_fireCooldown=0;_setupTimer=0;_packTimer=0;window._mortarDeployed=false;window._mortarShells=0;}
  return{init:init,update:update,deploy:deploy,fire:fire,pack:pack,reset:reset,damage:damage};
}());
